
//----------------------------------------------------
// The following code was generated by CUP v0.11a beta 20060608
// Sun Mar 11 12:35:23 EDT 2018
//----------------------------------------------------

/** CUP generated interface containing symbol constants. */
public interface sym {
  /* terminals */
  public static final int INT = 15;
  public static final int JOP = 5;
  public static final int COLON = 11;
  public static final int EOF = 0;
  public static final int ID = 14;
  public static final int COMMA = 12;
  public static final int HOP = 7;
  public static final int error = 1;
  public static final int REG = 13;
  public static final int RPAREN = 9;
  public static final int DOT_TEXT = 8;
  public static final int DOP = 6;
  public static final int ROP = 2;
  public static final int LPAREN = 10;
  public static final int IOP = 3;
  public static final int IOPM = 4;
}

